// Exports the unit catalog (slug + tier only) as a CommonJS module for the
// PocketBase JSVM hooks, which can't import the TS engine directly.
// Run: npm run export-catalog  (rerun whenever units are added)
import { createServer } from 'vite';
import { writeFileSync, mkdirSync } from 'node:fs';

const server = await createServer({ server: { middlewareMode: true }, logLevel: 'error' });
const { CATALOG } = await server.ssrLoadModule('/src/lib/engine/catalog.ts');
await server.close();

const minimal = CATALOG.map((u) => ({ slug: u.slug, tier: u.tier }));
mkdirSync('pb_hooks/lib', { recursive: true });
writeFileSync(
  'pb_hooks/lib/catalog.js',
  '// GENERATED by scripts/export-catalog.mjs — do not edit\n' +
    'module.exports = { CATALOG: ' +
    JSON.stringify(minimal) +
    ' };\n'
);
console.log(`Exported ${minimal.length} units to pb_hooks/lib/catalog.js`);
